"""add invites table

Revision ID: 0b64c13b9c22
Revises: 56d02a63fc4d
Create Date: 2026-04-27 01:00:08.663820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0b64c13b9c22'
down_revision = '56d02a63fc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('issued_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('invite', 'password_reset')", name='invites_kind_check'),
    sa.ForeignKeyConstraint(['consumed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('invites_email_idx', 'invites', ['email'], unique=False)
    op.create_index('invites_kind_active_idx', 'invites', ['kind'], unique=False, postgresql_where=sa.text('consumed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('invites_kind_active_idx', table_name='invites', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_index('invites_email_idx', table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
