"""add tanks table

Revision ID: 2d77fe37aaa6
Revises: 0b64c13b9c22
Create Date: 2026-04-27 13:57:18.645085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d77fe37aaa6'
down_revision = '0b64c13b9c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('water_type', sa.String(length=16), nullable=False),
    sa.Column('volume_liters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('setup_date', sa.Date(), nullable=True),
    sa.Column('decommission_date', sa.Date(), nullable=True),
    sa.Column('substrate', sa.String(length=256), nullable=True),
    sa.Column('equipment_notes', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('healthy', 'watch', 'unhealthy', 'unknown')", name='tanks_status_check'),
    sa.CheckConstraint("water_type IN ('fresh', 'salt', 'brackish')", name='tanks_water_type_check'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tanks_active_idx', 'tanks', ['created_at'], unique=False, postgresql_where=sa.text('decommission_date IS NULL'))
    op.create_index('tanks_decommissioned_idx', 'tanks', ['decommission_date'], unique=False, postgresql_where=sa.text('decommission_date IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tanks_decommissioned_idx', table_name='tanks', postgresql_where=sa.text('decommission_date IS NOT NULL'))
    op.drop_index('tanks_active_idx', table_name='tanks', postgresql_where=sa.text('decommission_date IS NULL'))
    op.drop_table('tanks')
    # ### end Alembic commands ###
